stages:
  - lint
  - publish

jobs:
  fix-whitespaces-with-vlna:
    stage: lint
    image: texlive/texlive
    script:
      - bash -c "vlna ./*.tex"
      - bash -c "rm ./*.te~"
    artifacts:
      paths:
        - *.tex
  
  commit-changes:
    stage: publish
    needs:
      - fix-whitespaces-with-vlna
   script:
      - |
        if [[ -z $(git status --untracked-files=no --porcelain) ]]; then
          echo "No unstaged changes present in the repository"
          exit 0
        fi
      - git add web.config alpske/web.config chorvatske/web.config chorvatsko-forum/web.config italske/web.config slovenske/web.config wwwRedirect/web.config
      - git config user.email "vlna@latex-project.org"
      - git config user.name "Grammar Nazi"
      - git remote set-url origin https://gitlab-ci-token:${CI_ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
      - git commit -m "🌊🌊🌊Vlna vibe check [skip ci]"
      - git push origin HEAD:$CI_COMMIT_REF_NAME -o ci.skip

